#!/usr/bin/env bash
#PBS -N bwa_<NUMBER>
#PBS -o bwa_<NUMBER>.out
#PBS -e bwa_<NUMBER>.err
#PBS -l select=1:ncpus=8:mem=32gb,walltime=48:00:00

cd /scratch1/jboatw2/BAP/variant_calling/results

export PATH=$PATH:/home/jboatw2/software/bin
# module add anaconda3/5.1.0-gcc/8.3.1

BASE_DIR="/scratch1/jboatw2/BAP/variant_calling"
OUTPUT_DIR="${BASE_DIR}/results/alignments"
NUM_CPUS=8
GENOME="${BASE_DIR}/data/references/Sbicolor_454_v3.0.1.fa"

DESIGN_FILE="${BASE_DIR}/doc/sample_names.txt"
DESIGN=$(cat ${DESIGN_FILE} | head -n <NUMBER> | tail -n 1)

IFS=',' read -ra ARRAY <<< "${DESIGN}"

READ_GROUP=${ARRAY[0]}
SAMPLE=$( echo "${ARRAY[0]}" | cut -f 1 -d '.' )

echo $READ_GROUP
echo $SAMPLE

R1="${BASE_DIR}/data/fastq/filtered/${READ_GROUP}_1.filt.fq.gz"
R2="${BASE_DIR}/data/fastq/filtered/${READ_GROUP}_2.filt.fq.gz"

if [ ! -e ${OUTPUT_DIR} ]
then
    mkdir -p ${OUTPUT_DIR}
fi

# load samtools from aligners env
# source activate aligners
~/bwa/bwa mem -t ${NUM_CPUS} -R "@RG\\tID:${READ_GROUP}\\tSM:${SAMPLE}\\tPL:Illumina" ${GENOME} ${R1} ${R2} | samtools view -t ${NUM_CPUS} -b - > ${OUTPUT_DIR}/${SAMPLE}.bam
