#!/usr/bin/env bash
#PBS -N jointGeno05_BAP
#PBS -e jointGeno05_BAP.err
#PBS -o jointGeno05_BAP.out
#PBS -l select=1:ncpus=6:mem=40gb,walltime=160:00:00
#PBS -q tillers

# tr '\n' ',' <  /scratch1/jboatw2/BAP_2057/doc/lines.txt | sed 's/,/.Chr${i}.vcf.gz -V /g'

BASE_DIR="/scratch1/jboatw2/BAP/variant_calling"
GVCF_PATH="${BASE_DIR}/results/single_gvcf"

echo "cd ${GVCF_PATH}"
cd ${GVCF_PATH}
echo "$PWD"

i="05"

~/gatk-4.2.6.1/gatk GenomicsDBImport --java-options "-Xmx34g -XX:+UseParallelGC -XX:ParallelGCThreads=2" \
    --genomicsdb-workspace-path ./BAP_Mace.Chr${i} -L Chr${i} \
    --batch-size 50 --reader-threads 5 --sample-name-map cohort.sample_map --tmp-dir "./tmp05"
