#!/usr/bin/env bash
#PBS -N recal_<SAMPLE>
#PBS -l select=1:ncpus=3:mem=20gb:interconnect=1g,walltime=160:00:00
#PBS -o recal_<SAMPLE>.out
#PBS -e recal_<SAMPLE>.err

BASE_DIR="/scratch1/jboatw2/BAP/variant_calling"
OUTPUT_PATH="${BASE_DIR}/results/recalibrated"
INPUT_PATH="${BASE_DIR}/results/marked_duplicates"
VCF_PATH="${BASE_DIR}/data/"

if [ ! -e ${OUTPUT_PATH} ]
then
    mkdir -p ${OUTPUT_PATH}
fi

cd ${INPUT_PATH}

samtools index ${INPUT_PATH}/<SAMPLE>.duplicate_marked.sorted.bam

~/gatk-4.2.6.1/gatk BaseRecalibrator \
    -I ${INPUT_PATH}/<SAMPLE>.duplicate_marked.sorted.bam \
    -R ${BASE_DIR}/data/references/Sbicolor_454_v3.0.1.fa \
    --known-sites ${VCF_PATH}/SAP.imputed.MAF_filtered.vcf.gz \
    -O ${OUTPUT_PATH}/recal_data.<SAMPLE>.table

~/gatk-4.2.6.1/gatk ApplyBQSR \
    --input ${INPUT_PATH}/<SAMPLE>.duplicate_marked.sorted.bam \
    --output ${OUTPUT_PATH}/<SAMPLE>.recalibrated.bam \
    --bqsr-recal-file ${OUTPUT_PATH}/recal_data.<SAMPLE>.table
